package entity;
// Generated 12/11/2021 10:32:51 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Ambiente generated by hbm2java
 */
public class Ambiente  implements java.io.Serializable {


     private Integer idAmbiente;
     private Zona zona;
     private float humedad;
     private float temperatura;
     private Date fechahr;

    public Ambiente() {
    }

    public Ambiente(Zona zona, float humedad, float temperatura, Date fechahr) {
       this.zona = zona;
       this.humedad = humedad;
       this.temperatura = temperatura;
       this.fechahr = fechahr;
    }
   
    public Integer getIdAmbiente() {
        return this.idAmbiente;
    }
    
    public void setIdAmbiente(Integer idAmbiente) {
        this.idAmbiente = idAmbiente;
    }
    public Zona getZona() {
        return this.zona;
    }
    
    public void setZona(Zona zona) {
        this.zona = zona;
    }
    public float getHumedad() {
        return this.humedad;
    }
    
    public void setHumedad(float humedad) {
        this.humedad = humedad;
    }
    public float getTemperatura() {
        return this.temperatura;
    }
    
    public void setTemperatura(float temperatura) {
        this.temperatura = temperatura;
    }
    public Date getFechahr() {
        return this.fechahr;
    }
    
    public void setFechahr(Date fechahr) {
        this.fechahr = fechahr;
    }




}


