package entity;
// Generated 12/11/2021 10:32:51 AM by Hibernate Tools 4.3.1



/**
 * Existencia generated by hbm2java
 */
public class Existencia  implements java.io.Serializable {


     private Integer idExistencia;
     private Producto producto;
     private Zona zona;
     private int cantidad;

    public Existencia() {
    }

    public Existencia(Producto producto, Zona zona, int cantidad) {
       this.producto = producto;
       this.zona = zona;
       this.cantidad = cantidad;
    }
   
    public Integer getIdExistencia() {
        return this.idExistencia;
    }
    
    public void setIdExistencia(Integer idExistencia) {
        this.idExistencia = idExistencia;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public Zona getZona() {
        return this.zona;
    }
    
    public void setZona(Zona zona) {
        this.zona = zona;
    }
    public int getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }




}


