package entity;
// Generated 12/11/2021 10:32:51 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Personal generated by hbm2java
 */
public class Personal  implements java.io.Serializable {


     private Integer idPersonal;
     private String ine;
     private Date fechaNac;
     private String teléfono;
     private String nombre;
     private String direccion;
     private Set viveros = new HashSet(0);
     private Set registros = new HashSet(0);

    public Personal() {
    }

	
    public Personal(String ine, Date fechaNac, String teléfono, String nombre, String direccion) {
        this.ine = ine;
        this.fechaNac = fechaNac;
        this.teléfono = teléfono;
        this.nombre = nombre;
        this.direccion = direccion;
    }
    public Personal(String ine, Date fechaNac, String teléfono, String nombre, String direccion, Set viveros, Set registros) {
       this.ine = ine;
       this.fechaNac = fechaNac;
       this.teléfono = teléfono;
       this.nombre = nombre;
       this.direccion = direccion;
       this.viveros = viveros;
       this.registros = registros;
    }
   
    public Integer getIdPersonal() {
        return this.idPersonal;
    }
    
    public void setIdPersonal(Integer idPersonal) {
        this.idPersonal = idPersonal;
    }
    public String getIne() {
        return this.ine;
    }
    
    public void setIne(String ine) {
        this.ine = ine;
    }
    public Date getFechaNac() {
        return this.fechaNac;
    }
    
    public void setFechaNac(Date fechaNac) {
        this.fechaNac = fechaNac;
    }
    public String getTeléfono() {
        return this.teléfono;
    }
    
    public void setTeléfono(String teléfono) {
        this.teléfono = teléfono;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public Set getViveros() {
        return this.viveros;
    }
    
    public void setViveros(Set viveros) {
        this.viveros = viveros;
    }

    public Set getRegistros() {
        return registros;
    }

    public void setRegistros(Set registros) {
        this.registros = registros;
    }

}


