package entity;
// Generated 12/11/2021 10:32:51 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Vivero generated by hbm2java
 */
public class Vivero  implements java.io.Serializable {


     private Integer idVivero;
     private Personal personal;
     private String nombre;
     private String teléfono;
     private String dirección;
     private Set zonas = new HashSet(0);

    public Vivero() {
    }

	
    public Vivero(Personal personal, String nombre, String teléfono, String dirección) {
        this.personal = personal;
        this.nombre = nombre;
        this.teléfono = teléfono;
        this.dirección = dirección;
    }
    public Vivero(Personal personal, String nombre, String teléfono, String dirección, Set zonas) {
       this.personal = personal;
       this.nombre = nombre;
       this.teléfono = teléfono;
       this.dirección = dirección;
       this.zonas = zonas;
    }
   
    public Integer getIdVivero() {
        return this.idVivero;
    }
    
    public void setIdVivero(Integer idVivero) {
        this.idVivero = idVivero;
    }
    public Personal getPersonal() {
        return this.personal;
    }
    
    public void setPersonal(Personal personal) {
        this.personal = personal;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getTeléfono() {
        return this.teléfono;
    }
    
    public void setTeléfono(String teléfono) {
        this.teléfono = teléfono;
    }
    public String getDirección() {
        return this.dirección;
    }
    
    public void setDirección(String dirección) {
        this.dirección = dirección;
    }
    public Set getZonas() {
        return this.zonas;
    }
    
    public void setZonas(Set zonas) {
        this.zonas = zonas;
    }




}


