package entity;
// Generated 12/11/2021 10:32:51 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Zona generated by hbm2java
 */
public class Zona  implements java.io.Serializable {


     private Integer idZona;
     private Vivero vivero;
     private String nombre;
     private String descripción;
     private Float superficie;
     private Set ambientes = new HashSet(0);
     private Set existencias = new HashSet(0);
     private Set registros = new HashSet(0);

    public Zona() {
    }

	
    public Zona(Vivero vivero, String nombre, String descripción, Float superficie) {
        this.vivero = vivero;
        this.nombre = nombre;
        this.descripción = descripción;
        this.superficie = superficie;
    }
    public Zona(Vivero vivero, String nombre, String descripción, Float superficie, Set ambientes, Set existencias, Set registros) {
       this.vivero = vivero;
       this.nombre = nombre;
       this.descripción = descripción;
       this.superficie = superficie;
       this.ambientes = ambientes;
       this.existencias = existencias;
       this.registros = registros;
    }

    public String getDescripción() {
        return descripción;
    }

    public void setDescripción(String descripción) {
        this.descripción = descripción;
    }
    
   
    public Integer getIdZona() {
        return this.idZona;
    }
    
    public void setIdZona(Integer idZona) {
        this.idZona = idZona;
    }
    public Vivero getVivero() {
        return this.vivero;
    }
    
    public void setVivero(Vivero vivero) {
        this.vivero = vivero;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public Float getSuperficie() {
        return this.superficie;
    }
    
    public void setSuperficie(Float superficie) {
        this.superficie = superficie;
    }
    public Set getAmbientes() {
        return this.ambientes;
    }
    
    public void setAmbientes(Set ambientes) {
        this.ambientes = ambientes;
    }
    public Set getExistencias() {
        return this.existencias;
    }
    
    public void setExistencias(Set existencias) {
        this.existencias = existencias;
    }

    public Set getRegistros() {
        return registros;
    }

    public void setRegistros(Set registros) {
        this.registros = registros;
    }

    


}


